export const shoptypes = {
	SHOP_COLLECTION_ITEMS: "SHOP_COLLECTION_ITEMS",
	SHOP_COLLECTIONS_START: "SHOP_COLLECTIONS_START",
	SHOP_COLLECTIONS_SUCCESS: "SHOP_COLLECTIONS_SUCCESS",
	SHOP_COLLECTIONS_FAILURE: "SHOP_COLLECTIONS_FAILURE",
}
