const actionTypes = {
	SET_CURRENT_USER: "SET_CURRENT_USER",
	SIGNIN_WITH_GOOGLE_START: "SIGNIN_WITH_GOOGLE_START",
	SIGNIN_WITH_GOOGLE_SUCCESS: "SIGNIN_WITH_GOOGLE_SUCCESS",
	SIGNIN_WITH_GOOGLE_FAILED: "SIGNIN_WITH_GOOGLE_FAILED",
	SIGNIN_WITH_EMAIL_START: "SIGNIN_WITH_EMAIL_START",
	SIGNIN_WITH_EMAIL_SUCCESS: "SIGNIN_WITH_EMAIL_SUCCESS",
	SIGNIN_WITH_EMAIL_FAILED: "SIGNIN_WITH_EMAIL_FAILED",
	SIGNUP_WITH_EMAIL_START: "SIGNUP_WITH_EMAIL_START",
	SIGNUP_WITH_EMAIL_SUCCESS: "SIGNUP_WITH_EMAIL_SUCCESS",
	SIGNUP_WITH_EMAIL_FAILED: "SIGNUP_WITH_EMAIL_FAILED",
	CURRENT_USER_START: "CURRENT_USER_START",
	CURRENT_USER_SUCCESS: "CURRENT_USER_SUCCESS",
	CURRENT_USER_FAILURE: "CURRENT_USER_FAILURE",
}
export default actionTypes
